image: mcr.microsoft.com/dotnet/sdk:9.0-noble

stages:
  - deploy
  - postdeploy

create-pages:
  stage: deploy
  pages:
    publish: aptivi.github.io/bin/Release/net9.0/publish/wwwroot
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - apt update
    - apt -y install python-is-python3
    - dotnet workload install wasm-tools
    - sed -i 's|base href="/"|base href="/aptivi-github-io/"|g' aptivi.github.io/wwwroot/index.html
  script:
    - dotnet publish --configuration Release
    - cp aptivi.github.io/bin/Release/net9.0/publish/wwwroot/index.html
      aptivi.github.io/bin/Release/net9.0/publish/wwwroot/404.html

gh-pages:
  stage: postdeploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - sed -i 's|base href="/aptivi-github-io/"|base href="/"|g' aptivi.github.io/bin/Release/net9.0/publish/wwwroot/index.html
    - git fetch --all
    - git checkout gh-pages
    - cp -a aptivi.github.io/bin/Release/net9.0/publish/wwwroot/* .
    - rm -r aptivi.github.io
    - git add .
    - git config user.email "ceo@aptivi.anonaddy.com"
    - git config user.name "Aptivi"
    - git commit -m "Deployed from $CI_COMMIT_SHA"
    - 'git remote add github https://AptiviCEO:${GH_APIKEY}github.com/Aptivi/aptivi.github.io'
    - git push github
