image: mcr.microsoft.com/dotnet/sdk:9.0-noble
create-pages:
  pages:
    publish: aptivi.github.io/bin/Release/net9.0/publish/wwwroot
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - apt update
    - apt -y install python-is-python3
    - dotnet workload install wasm-tools
    - sed -i 's|base href="/"|base href="/aptivi-github-io/"|g' aptivi.github.io/wwwroot/index.html
  script:
    - dotnet publish --configuration Release
    - cp aptivi.github.io/bin/Release/net9.0/publish/wwwroot/index.html
      aptivi.github.io/bin/Release/net9.0/publish/wwwroot/404.html
