# The Docker image that will be used to build your app
image: mcr.microsoft.com/dotnet/aspnet:9.0-noble
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: aptivi.github.io/bin/Release/net9.0/publish/wwwroot
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  before_script:
    - dotnet workload install wasm-tools
  script:
    - dotnet publish --configuration Release
    - cp aptivi.github.io/bin/Release/net9.0/publish/wwwroot/index.html
      aptivi.github.io/bin/Release/net9.0/publish/wwwroot/404.html
