name: 'Publish application'
on: push

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    env:
      PUBLISH_FOLDER: /home/runner/work/aptivi.github.io/aptivi.github.io/aptivi.github.io/bin/Release/net8.0/publish/wwwroot

    name: Build and Deploy Job
    steps:
      - name: Set the name of the repo in env variable 
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
        
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
   
      - name: Publish the website in its release form
        run: |
          dotnet workload install wasm-tools
          dotnet publish --configuration Release
  
      - name: copy index.html to 404.html
        run: cp $PUBLISH_FOLDER/index.html $PUBLISH_FOLDER/404.html
      
      - name: Add .nojekyll file
        run: touch $PUBLISH_FOLDER/.nojekyll
        
      - name: Deploy GitHub Pages action
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.G_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ${{ env.PUBLISH_FOLDER }}
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
