name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Generate the site map (site)
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://aptivi.github.io/

    - name: Generate the site map (Kernel Simulator (TEST))
      id: sitemap-ks
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://aptivi.github.io/Kernel-Simulator/

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.0.4
      with:
        title: "Automated sitemap update"
        body: > 
          Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
          GitHub action.  
        commit-message: "Automated sitemap update."
        branch: create-pull-request/sitemap
        delete-branch: true